//creating quiz
export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILURE = "CREATE_QUIZ_FAILURE";

//get thumbnails
export const GET_THUMBNAIL_REQUEST = "GET_THUMBNAIL_REQUEST";
export const GET_THUMBNAIL_SUCCESS = "GET_THUMBNAIL_SUCCESS";
export const GET_THUMBNAIL_FAILURE = "GET_THUMBNAIL_FAILURE";
//get quiz
export const GET_SINGLE_QUIZ_REQUEST = "GET_SINGLE_QUIZ_REQUEST";
export const GET_SINGLE_QUIZ_SUCCESS = "GET_SINGLE_QUIZ_SUCCESS";
export const GET_SINGLE_QUIZ_FAILURE = "GET_SINGLE_QUIZ_FAILURE";
//register user
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
//login user
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
//logout user
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
//set user
export const SET_USER = "SET_USER";
//post user to server
export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILURE = "POST_USER_FAILURE";
//post result to redux
export const POST_USER_RESULT_REQUEST = "POST_USER_RESULT_REQUEST";
export const POST_USER_RESULT_SUCCESS = "POST_USER_RESULT_SUCCESS";
export const POST_USER_RESULT_FAILURE = "POST_USER_RESULT_FAILURE";
//post result to redux
export const SET_USER_RESULT_SUCCESS = "SET_USER_RESULT_SUCCESS";