//creating quiz
export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILURE = "CREATE_QUIZ_FAILURE";

//get thumbnails
export const GET_THUMBNAIL_REQUEST = "GET_THUMBNAIL_REQUEST";
export const GET_THUMBNAIL_SUCCESS = "GET_THUMBNAIL_SUCCESS";
export const GET_THUMBNAIL_FAILURE = "GET_THUMBNAIL_FAILURE";
//get quiz
export const GET_SINGLE_QUIZ_REQUEST = "GET_SINGLE_QUIZ_REQUEST";
export const GET_SINGLE_QUIZ_SUCCESS = "GET_SINGLE_QUIZ_SUCCESS";
export const GET_SINGLE_QUIZ_FAILURE = "GET_SINGLE_QUIZ_FAILURE";
